import "./globals.css";
import Darkmodetoggle from "@/components/buttons/Darkmodetoggle.js";
import BgAnimation from "@/components/ui/BgAnimation";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Tech Showroom",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="dark:bg-black">
            <body
                className={`${inter.className} `}
            >
                <div className=" inset-0 overflow-y-scroll w-screen ">
                    <Darkmodetoggle />
                    <Toaster position="bottom-left" reverseOrder={false} />
                    <div className=" max-w-7xl bg-white dark:bg-black pb-10w rounded-xl dark:bg-opacity-50 bg-opacity-50 mx-auto">
                        <div className="px-3 sm:px-11 md:px-13 lg:px-14 ">
                            {children}
                        </div>
                    </div>
                </div>
                <BgAnimation />
            </body>
        </html>
    );
}
